### PR TITLE
SPIKE: Stencil.js

### PR DESCRIPTION
**Pull request by joebell93**
## Description

As a platform agnostic framework, it makes sense to explore the possibility of using [Stencil.js](https://stenciljs.com/) (web component compiler)

Is Stencil worth adopting? (TBC)

This PR will be taking/converting components from the internal React.js library to investigate.

## Related Issue

N/A

## Motivation and Context

Consolidation of tech and design

## How Has This Been Tested?

TBC

## Markup

TBC

## Types of Changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [ ] Internal *(framework-only)*
- [ ] Bug Fix *(non-breaking change which fixes an issue)*
- [ ] New Feature *(non-breaking change which adds functionality)*
- [x] Breaking change *(fix or feature that would cause existing functionality to change)*

## Browser Support

- [ ] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] IE9
- [ ] IE10
- [ ] IE11
- [ ] Opera
- [ ] Safari
- [ ] Mobile Devices
- [ ] Screen-readers (e.g. JAWS, Apple VoiceOver)

## Checklist

- [ ] All **design and code** conforms to the [Design Contribution Guidelines](https://github.com/sky-uk/toolkit/blob/develop/CONTRIBUTING.md#design-contributions).
- [ ] New functions and mixins have appropriate tests.
- [ ] All new and existing tests passed.
- [ ] I have added instructions on how to test my changes.

### CODE REVIEW

**Comment by skitson** [comment]
I had a quick play with Stencil over the weekend. I think it's quite nice. I haven't worked out how the components are platform agnostic yet though so can't really comment on it in that sense.

**Comment by beclamide** [comment]
Stencil components compile to native web components. You can use them in any front-end framework because the browser sees the component as if it's a standard HTML element.

An excerpt from : https://medium.com/@sinedied/stencil-js-its-finally-time-for-vanilla-web-components-927d26b573e1

```
So can we throw Angular, React, VueJS…?
Not yet, and far from it! 😄

Even if it’s possible to make complete apps and websites with Stencil (the stenciljs.com website is an example), it’s not its primary goal: the idea is to create collections of components that can be used independently from a framework.

The first major “client” is the Ionic framework itself, with the next major version being announced as compatible with Angular, React, VueJS, Riot and others… and even maybe Angular 1.x!

It’s also very interesting for enterprise in-house components, so they can be developed and shared among many apps regardless of their framework stack. It may also lessen the pain of upgrade/migrations between different framework/versions (who said Angular 1.x to 2 migration?).
```

Also worth reading: https://hackernoon.com/consuming-a-stencil-component-in-react-app-aa3f37f9e49a

**Comment by skitson** [comment]
Thanks for the info above @beclamide - looks fairly painless using a Stencil component in a React app. Just wondering - it's great that we can do this but if we know which framework we're using (React) is it better to just use that framework's components instead?

**Comment by joebell93** [comment]
Nicely put @beclamide!

**Comment by joebell93** [comment]
Don't think I'll have the time to look at this again before I leave unfortunately, so closing

**Pull request closed without merging**
