### PR TITLE
Subsection Dividers

### PR DESCRIPTION
**Pull request by joebell93**
# Description
New `c-divider--sub` modifier to remove the shadow from dividers. This works on **all** existing dividers by resetting the pseudo-element.

Additional modifiers can be passed to `--align-left` or `--align-right`.

## Related Issue

#307

## Motivation and Context

Alignment with design.

## How Has This Been Tested?

Browser tested.

## Markup

```
<hr class="c-divider c-divider--sub" />
<hr class="c-divider c-divider--sub c-divider--align-left" />
<hr class="c-divider c-divider--sub c-divider--align-right" />
```

## Screenshots

screen shot 2018-04-13 at 10 16 05

## Types of Changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Browser Support

- [x] Chrome
- [x] Edge
- [x] Firefox
- [x] IE9 (falls back to standard keyline)
- [x] IE10
- [x] IE11
- [x] Opera
- [x] Safari
- [x] Mobile Devices
- [x] Screen-readers (e.g. JAWS, Apple VoiceOver)

## Checklist

- [x] All **design and code** conforms to the [Design Contribution Guidelines](https://github.com/sky-uk/toolkit/blob/develop/CONTRIBUTING.md#design-contributions).
- [x] New functions and mixins have appropriate tests.
- [x] All new and existing tests passed.
- [x] I have added instructions on how to test my changes.

### CODE REVIEW

**Comment by joebell93** [comment]
This is ready to go pending @mikejgregory's update to the internal Sketch Library

**Comment by MrDinsdale** [comment]
@mikejgregory @joebell93  Have we ditched the concept of left and right aligned sub section dividers now? If so, fantastic but we should remove them from the original issue.

**Comment by joebell93** [comment]
@MrDinsdale agreed that would also be fantastic, but I've suggested we tackle that in a different release at it may require refactoring :'(

**Comment by MrDinsdale** [comment]
Is it wise to implement to implement this knowing that it will definitely cause a breaking change rather than investigate implementing the full version?

**Comment by joebell93** [comment]
Sorry to clear up, not necessarily a breaking change but some refactoring of our mixin. It makes sense to separate this out and provide the feature first

Likelihood is a `c-divider--left-align`

**Comment by MrDinsdale** [comment]
I'm just concerned that with out spiking this out and having a clear solution of how this might work once fully implemented, we may well be writing new functionality we know we will deprecate where not needed. I would feel a little more comfortable if we had a solid plan for how the sub section with the alignment would work as having a modifier such as `c-divider--left-align` which is only compatible with another modifier `c-divider--sub` feels like an anti-pattern.

I'm not sure modifiers for the divider are necessarily the best approach in the long term. I'd like to get other peoples opinions but I won't hold the PR if the general consensus is to go ahead.

**Comment by joebell93** [comment]
Can understand your concern but this is something defined in the Sketch Library (it only applies to sub dividers) - it's not a pattern we are setting in Toolkit, it's one we are following.

Myself and @mikejgregory also agree it's a bit of a mouthful so perhaps it's worth revisiting, this is primarily why I think it's worth addressing in a different PR as it's a totally different concern. 

imo there's no reason to block the release of Subdividers, as we can always release additional non-breaking changes later.

If you think there's a better approach instead of modifiers, I'd welcome any ideas

**Comment by skitson** [comment]
I think we should deal with the alignment stuff in another PR.

**Comment by MrDinsdale** [comment]
PS when I say spike I mean a very high level i.e. what might the classes be and how would they be composed for the different variations. I'm not too concerned with what happens within the CSS, just that we don't cause users pain which could be avoided.

**Comment by joebell93** [comment]
I've already completed a high-level spike for that, with the classes I'm proposing in the comment above - that way it **could** be applied to either the divider or sub divider

It's a different feature altogether imo and requires additions to both the core and ui

**Comment by MrDinsdale** [comment]
My concern with this implementation (and proposed future solution) is that we are either:

a) creating modifiers which enable styling to be out of alignment with design i.e. `c-divider c-divider--align-left`.
b) creating a modifier only compatible with another modifier i.e. `c-divider--sub` and `c-divider--align-left` which is an anti-pattern.
c) implementing a quick fix which we are going to deprecate causing consumers pain that could easily be avoided.

Before we make changes we should confirm with design that this left/right aligned sub divider is required and if its ok that we allow the same behaviour for `c-divider`. Based on that feedback we can determine which of the above has the least friction for end user and produces the cleanest implementation without deviating from our design assets.

**Comment by MrDinsdale** [comment]
I'll be honest, I think I'd still prefer a separate component to make sure its easy for the end users to implement but happy to go with everyone else on this one. Given the approach I the implementation is solid.

My only comment would be that the docs could reinforce the need for both modifiers for sub dividers but aside from that all good!

**Comment by joebell93** [comment]
Cheers @MrDinsdale, personally I'd still question what you mean by "easy". I'm not sure I see what's easier vs. harder I think they're fairly equal in terms of usage!

Do you think the modifier subheadings being inside `### Subsection` aren't clear enough?

**Comment by MrDinsdale** [comment]
I just think the `left`/`align-left` stuff is a little confusing especially when you add dependancies on other modifiers. It's not a big issue but seems likely to catch people out or result in unexpected behaviour.

I was thinking just a note to say the `align` modifiers are only compatible with `sub` but to be fair I guess it is already covered.

**Pull request merged**
