### PR TITLE
Back Links

### PR DESCRIPTION
**Pull request by joebell93**
## Description

* Add Back Links
* Add Back Links to Panels
* Tidy up and align our existing Base64 icons

## Related Issue

#313 

## Motivation and Context

Design Alignment

## Markup

`<a href="#" class="c-link-back">I'm a back link</a>`

## Screenshots

screen shot 2017-11-30 at 17 01 27

## Types of Changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Browser Support

- [x] Chrome
- [x] Edge
- [x] Firefox
- [x] IE9
- [x] IE10
- [x] IE11
- [x] Opera
- [x] Safari
- [x] Mobile Devices
- [x] Screen-readers (e.g. JAWS, Apple VoiceOver)

## Checklist

- [x] All **design and code** conforms to the [Design Contribution Guidelines](https://github.com/sky-uk/toolkit/blob/develop/CONTRIBUTING.md#design-contributions).
- [x] New functions and mixins have appropriate tests.
- [x] All new and existing tests passed.
- [x] I have added instructions on how to test my changes.

### CODE REVIEW

**Comment by MrDinsdale** [comment]
Could we get some mockups in context with the close button to check alignment?

**Comment by joebell93** [comment]
@MrDinsdale you beat me to it by about 60 seconds, hold up!

**Comment by joebell93** [comment]
## Demo

https://codepen.io/joebell/full/pdqQrP/

**Comment by mikejgregory** [comment]
Looks good to me.  One is the alignment with the close button, I think this is an issue with the close button though not the back.

**Comment by joebell93** [comment]
Yeah absolutely, I've left some notes on this in the original issue #313

**Pull request merged**
